version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    command: --port=3609
    ports:
      - "3609:3609"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-P", "3609", "-u", "${MYSQL_USER}", "--password=${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql+pymysql://root:rootpassword@db:3609/fake-data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 300M

volumes:
  mysql_data: